codes = [
{"name":"Goiânia","IATA":"GYN"},
{"name":"Rio Verde","IATA":"RVD"},
{"name":"Caldas Novas","IATA":"CLV"},
{"name":"Catalão","IATA":"TLZ"},
{"name":"Brasília","IATA":"BSB"},
{"name":"Alta Floresta","IATA":"AFL"},
{"name":"Barra dos Garças","IATA":"BPG"},
{"name":"Cáceres","IATA":"CCX"},
{"name":"Cuiabá","IATA":"CGB"},
{"name":"Rondonópolis",  "IATA":"ROO"},
{"name":"Tangará da Serra", "IATA":"TGQ"},
{"name":"Sinop","IATA":"OPS"},
{"name":"Sorriso", "IATA":"SMT"},
{"name":"Bonito", "IATA":"BYO"},
{"name":"Cassilândia", "IATA":"CSS"},
{"name":"Campo Grande", "IATA":"CGR"},
{"name":"Corumbá", "IATA":"CMG"},
{"name":"Dourados", "IATA":"DOU"},
{"name":"Paranaíba","IATA":"PBB"},
{"name":"Ponta Porã","IATA":"PMG"},
{"name":"Três Lagoas","IATA":"TJL"},
{"name":"Cruzeiro do Sul","IATA":"CZS"},
{"name":"Rio Branco","IATA":"RBR"},
{"name":"Macapá","IATA":"MCP"},
{"name":"Barcelos","IATA":"BAZ"},
{"name":"Boca do Acre","IATA":"BCR"},
{"name":"Borba", "IATA":"RBB"},
{"name":"Carauari", "IATA":"CAF"},
{"name":"Coari", "IATA":"CIZ"},
{"name":"Eirunepé", "IATA":"ERN"},
{"name":"Fonte Boa", "IATA":"FBA"},
{"name":"Humaitá", "IATA":"HUW"},
{"name":"Itacoatiara", "IATA":"ITA"},
{"name":"Lábrea", "IATA":"LBR"},
{"name":"Manaus", "IATA":"MAO"},
{"name":"Manicoré", "IATA":"MNX"},
{"name":"Maués", "IATA":"MBZ"},
{"name":"Novo Aripuanã", "IATA":"NVP"},
{"name":"Parintins ", "IATA":"PIN"},
{"name":"Santa Isabel do Rio Negro", "IATA":"IRZ"},
{"name":"Santo Antônio do Içá", "IATA":"IPG"},
{"name":"São Gabriel da Cachoeira", "IATA":"SJL"},
{"name":"São Paulo de Olivença", "IATA":"OLC"},
{"name":"Tabatinga", "IATA":"TBT"},
{"name":"Tefé", "IATA":"TFF"},
{"name":"Altamira", "IATA":"ATM"},
{"name":"Belém","IATA":"BEL"},
{"name":"Carajás","IATA":"CKS"},
{"name":"Itaituba","IATA":"ITB"},
{"name":"Marabá","IATA":"MAB"},
{"name":"Santarém","IATA":"STM"},
{"name":"Porto Velho","IATA":"PVH"},
{"name":"Ji Paraná","IATA":"JPR"},
{"name":"Cacoal","IATA":"OAL"},
{"name":"Vilhena","IATA":"BVH"},
{"name":"Boa Vista","IATA":"BVB"},
{"name":"Araguaína","IATA":"AUX"},
{"name":"Arraias","IATA":"AAI"},
{"name":"Dianópolis","IATA":"DNO"},
{"name":"Gurupi","IATA":"GRP"},
{"name":"Miracema do Tocantins","IATA":"NTM"},
{"name":"Palmas","IATA":"PMW"},
{"name":"Porto Nacional","IATA":"PNB"},
{"name":"Taquatinga","IATA":"QHN"},
{"name":"Arapiraca","IATA":"APQ"},
{"name":"Maceió","IATA":"MCZ"},
{"name":"Barreiras","IATA":"BRA"},
{"name":"Feira de Santana","IATA":"FEC"},
{"name":"Lençóis","IATA":"LEC"},
{"name":"Paulo Afonso","IATA":"PAV"},
{"name":"Porto Seguro","IATA":"BPS"},
{"name":"Salvador","IATA":"SSA"},
{"name":"Teixeira de Freitas","IATA":"TXF"},
{"name":"Valença","IATA":"VAL"},
{"name":"Vitória da Conquista","IATA":"VDC"},
{"name":"Fortaleza","IATA":"FOR"},
{"name":"Jericoacoara","IATA":"JJD"},
{"name":"Juazeiro do Norte	","IATA":"JDO"},
{"name":"Imperatriz","IATA":"IMP"},
{"name":"São Luís","IATA":"SLZ"},
{"name":"Campina Grande","IATA":"CPV"},
{"name":"João Pessoa","IATA":"JPA"},
{"name":"Caruaru","IATA":"CAU"},
{"name":"Fernando de Noronha","IATA":"FEN"},
{"name":"Petrolina","IATA":"PNZ"},
{"name":"Recife","IATA":"REC"},
{"name":"Serra Talhada","IATA":"SET"},
{"name":"Parnaíba","IATA":"PHB"},
{"name":"Teresina","IATA":"THE"},
{"name":"Mossoró","IATA":"MVF"},
{"name":"Natal","IATA":"NAT"},
{"name":"Aracaju","IATA":"AJU"},
{"name":"Vitória","IATA":"VIX"},
{"name":"Cachoeiro de Itapemirim","IATA":"CDI"},
{"name":"Guarapari","IATA":"GUZ"},
{"name":"São Mateus	","IATA":"SBJ"},
{"name":"Barbacena","IATA":"QAK"},
{"name":"Patos de Minas","IATA":"POJ"},
{"name":"Confins","IATA":"CNF"},
{"name":"Divinópolis","IATA":"DIQ"},
{"name":"Governador Valadares","IATA":"GVR"},
{"name":"Juiz de Fora","IATA":"JDF"},
{"name":"Montes Claros","IATA":"MOC"},
{"name":"Pampulha","IATA":"PLU"},
{"name":"Poços de Caldas","IATA":"POO"},
{"name":"São João del-Rei","IATA":"JDR"},
{"name":"Uberlândia	","IATA":"UDI"},
{"name":"Uberaba","IATA":"UBA"},
{"name":"Zona da Mata","IATA":"IZA"},
{"name":"Bartolomeu de Gusmão","IATA":"SNZ"},
{"name":"Campos dos Goytacazes","IATA":"CAW"},
{"name":"Cabo Frio","IATA":"CFB"},
{"name":"Galeão","IATA":"GIG"},
{"name":"Itaperuna","IATA":"ITP"},
{"name":"Macaé","IATA":"MEA"},
{"name":"Resende","IATA":"QRZ"},
{"name":"Santos Dumont","IATA":"SDU"},
{"name":"Araçatuba","IATA":"ARU"},
{"name":"Araraquara","IATA":"AQA"},
{"name":"Assis","IATA":"AIF"},
{"name":"Avaré/Arandu","IATA":"QVP"},
{"name":"Barretos","IATA":"BAT"},
{"name":"Bauru/Arealva","IATA":"JTC"},
{"name":"Botucatu","IATA":"QCP"},
{"name":"Bragança Paulista","IATA":"BJP"},
{"name":"Campo dos Amarais ","IATA":"CPQ"},
{"name":"Congonhas","IATA":"CGH"},
{"name":"Dracena","IATA":"QDC"},
{"name":"Guaratinguetá","IATA":"GUJ"},
{"name":"Guarulhos","IATA":"GRU"},
{"name":"Franca","IATA":"FRC"},
{"name":"Jundiaí","IATA":"QDV"},
{"name":"Lençóis Paulista ","IATA":"QGC"},
{"name":"Lins","IATA":"LIP"},
{"name":"Marília","IATA":"MII"},
{"name":"Ourinhos","IATA":"OUS"},
{"name":"Piracicaba ","IATA":"QHB"},
{"name":"Presidente Prudente","IATA":"PPB"},
{"name":"Ribeirão Preto","IATA":"RAO"},
{"name":"São Carlos","IATA":"QSC"},
{"name":"São José do Rio Preto","IATA":"SJP"},
{"name":"São José dos Campos","IATA":"SJK"},
{"name":"Sorocaba","IATA":"SOD"},
{"name":"Ubatuba","IATA":"UBT"},
{"name":"Viracopos","IATA":"VCP"},
{"name":"Votuporanga","IATA":"VOT"},
{"name":"Região","IATA":"Sul"},
{"name":"Cascavel","IATA":"CAC"},
{"name":"Curitiba","IATA":"CWB"},
{"name":"Foz do Iguaçu","IATA":"IGU"},
{"name":"Londrina","IATA":"LDB"},
{"name":"Maringá","IATA":"MGF"},
{"name":"Ponta Grossa","IATA":"PGZ"},
{"name":"Umuarama","IATA":"UMU"},
{"name":"Bagé","IATA":"BGX"},
{"name":"Caxias do Sul","IATA":"CXJ"},
{"name":"Passo Fundo","IATA":"PFB"},
{"name":"Porto Alegre","IATA":"POA"},
{"name":"Santa Maria","IATA":"RIA"},
{"name":"Uruguaiana","IATA":"URG"},
{"name":"Blumenau","IATA":"BNU"},
{"name":"Chapecó","IATA":"XAP"},
{"name":"Forquilhinha","IATA":"CCM"},
{"name":"Florianópolis","IATA":"FLN"},
{"name":"Jaguaruna","IATA":"JJG"},
{"name":"Joaçaba","IATA":"JCB"},
{"name":"Joinville","IATA":"JOI"},
{"name":"Lages","IATA":"LAJ"},
{"name":"Navegantes","IATA":"NVT"}
]